title : "> Native Build"
description: "Blog sobre desenvolvimento de aplicativos para smartphones com JavaScript, HTML5 e CSS3"

safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:    /
url: http://nativebuild.com
paginate: 5

source:      ./_source
destination: ./_site
plugins:     ./_source/_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink: /:year/:title.html